schema_version: 1

context:
  name: tauloa
  version: "1.1.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://tauolapp.web.cern.ch/tauolapp/resources/TAUOLA.${{ version }}/TAUOLA.${{ version }}-LHC.tar.gz
  sha256: 4eb69f38bc0163568034f95b47d1ae461becbff9935921d57e49d3583cb3c158

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - make
    - autoconf
    - automake
    - libtool
    - if: unix
      then: gnuconfig
    - pkg-config
  host:
    - hepmc2
    - hepmc3
  run:
    - ${{ pin_compatible('hepmc2', upper_bound="x.x.x") }}
    - ${{ pin_compatible('hepmc3', upper_bound="x.x.x") }}
  run_exports:
    - ${{ pin_subpackage('tauloa', upper_bound='x.x.x') }}

tests:
  - script:
      - "test -f \"${PREFIX}/lib/libTauolaCxxInterface$SHLIB_EXT\""
      - "test -f \"${PREFIX}/lib/libTauolaFortran$SHLIB_EXT\""
      - "test -f \"${PREFIX}/lib/libTauolaHEPEVT$SHLIB_EXT\""
      - "test -f \"${PREFIX}/lib/libTauolaHepMC$SHLIB_EXT\""
      - "test -f \"${PREFIX}/lib/libTauolaHepMC3$SHLIB_EXT\""

about:
  license: GPL-3.0-only
  license_file: COPYING
  summary: Package for simulating tau lepton decays
  homepage: https://tauolapp.web.cern.ch/tauolapp/
  documentation: http://tauolapp.web.cern.ch/tauolapp/resources/TAUOLA.${{ version }}/Tauola_interface_design.${{ version }}.pdf

extra:
  recipe-maintainers:
    - chrisburr
